//PROVIDES KNOWN PROCESS NAMES AND THE FILES THEY MAP TO

const ProcessNames = {
    BOOTSTRAP : "process-BOOTSTRAP", //CRITICAL PROCESS 
    TEST: "process-TEST", //PLACEHOLDER PROCESS TO TEST PROCESS TABLE
}
module.exports = ProcessNames

