const ProcessStatus = {
    RUNNING: 1,
    KILLED: -1,
    WAITING_ON_CHILD: 2, //FOR WHEN THE PROCESS SPAWNED A CHILD PROCESS AND NEEDS THAT ONE TO COMPLETE
    WAITING_ON_TICK: 3,  //FOR WHEN THE PROCESS IS WAITING ON THE GAME TO ADVANCE TO THE NEXT TICK

}