const ProcessStatus = {
    RUNNING: 1,
    INITIALIZING: 0, //PROCESS SHOULD RUN ANY MEMORY INITIALIZATION CODE REQUIRED BEFORE FIRST RUN
    KILLED: -1,
    WAITING_ON_CHILD: 2, //FOR WHEN THE PROCESS SPAWNED A CHILD PROCESS AND NEEDS THAT ONE TO COMPLETE
    WAITING_ON_TICK: 3,  //FOR WHEN THE PROCESS IS WAITING ON THE GAME TO ADVANCE TO THE NEXT TICK

}

module.exports = ProcessStatus;